### ISSUE TITLE
Not getting expected result/performance by Flownet2 model on FlyingChair Dataset.

### ISSUE THREAD

**Issue by nudlesoup** [NVIDIA/flownet2-pytorch#216]
Hi I am running inference on the given Dataset and not able to get expected results : 
These are my envs :
Env 1 on  conda : 
Linux Ubuntu - 14.4.6 
Tesla K40c GPU
Cuda 9.0.176 
py 3.6
pytorch 1.0.0 - py3.6_cuda9.0.176_cudnn7.4.1_1
cuda 90 
gcc-6 v6.1
torchvision 0.2.2
When i run install.sh i get these warnings but **no errors**. 

gcc -pthread -B /home/***/miniconda3/envs/test1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/TH -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/***/miniconda3/envs/test1/include/python3.6m -c correlation_cuda.cc -o build/temp.linux-x86_64-3.6/correlation_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from correlation_cuda.cc:1:0:
/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^~~~~~~
correlation_cuda.cc: In function ‘int correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int)’:
correlation_cuda.cc:44:7: warning: unused variable ‘success’ [-Wunused-variable]
   int success = correlation_forward_cuda_kernel(
       ^~~~~~~
/usr/local/cuda/bin/nvcc -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/TH -I/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/***/miniconda3/envs/test1/include/python3.6m -c correlation_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6

**I am able to run inference** but get the following warning and poor result.

error in correlation_forward_cuda_kernel: CUDA driver version is insufficient for CUDA runtime 
/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/***/miniconda3/envs/test1/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
This is my results
![000000-vis](https://user-images.githubusercontent.com/39743142/84028045-4f5b7500-a990-11ea-8da3-f0918e610294.png)

while expected result is : 
![0000007-gt flo](https://user-images.githubusercontent.com/39743142/84028033-49659400-a990-11ea-9be8-8c53f4c25cf3.png)

For 2nd env :
Linux Ubuntu - 14.4.6 
Tesla K40c GPU
Cuda 9.0.176 
py 3.6
pytorch 1.0.0 - py3.6_cuda9.0.176_cudnn7.4.1_1
cuda 90 
gcc-5 5.4
torchvision 0.2.2

I get same poor results as above. But during inference i get this error :
error in correlation_forward_cuda_kernel: no kernel image is available for execution on the device
/home/***/anaconda3/envs/flow/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/home/***/anaconda3/envs/flow/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

**Comment by labdeeman7** [comment]
I have a similar error as well with MPI Sintel dataset, when I visualize the flo file, I get blurred images.
![000019 flo](https://user-images.githubusercontent.com/22771794/86520943-0937eb00-be42-11ea-960a-390308de61f5.png)

 I also have the same warning when running install.sh and the same error when I perform inference : error in correlation_forward_cuda_kernel: CUDA driver version is insufficient for CUDA runtime version

My environment is colab 
Tesla K40c GPU
Cuda 9.0.176
py 3.6
pytorch 1.0.0 
cuda 90
gcc-6 v6.1
torchvision 0.2.1

**Comment by coly-ai** [comment]
@labdeeman7 @nudlesoup  Hey guys, Have you ever solve the problem? I met totally same problem on other dataset. How to solve it？ Appreciate it！
![000000 flo](https://user-images.githubusercontent.com/70585435/91861323-416f7480-ec9f-11ea-8d8c-613c25324c2c.png)

**Comment by wgh-2018** [comment]
I encounter the same issue, have you solve the problem? thx

**Comment by nudlesoup** [comment]
Hi if anyone is still interested.
I was able to fix this then by using a older version of networks folders, using these ones 
https://github.com/nudlesoup/OpticalFlow-Flownet/tree/master/networks

Do check that out and see if it works
